---
version: "3.3"
services:
  frontend1:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: frontend1
    hostname: frontend1 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PUBLIC_KEY_FILE=/config/id_rsa.pub
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=frontend #optional
    volumes:
      - ./config-frontend1:/config
      - ./config-frontend1/index.html:/usr/share/nginx/html/index.html
    ports:
      - 2222:2222
      - 8080:80
    restart: unless-stopped
  frontend2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: frontend2
    hostname: frontend2 #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PUBLIC_KEY_FILE=/config/id_rsa.pub
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=frontend #optional
    volumes:
      - ./config-frontend2:/config
      - ./config-frontend2/index.html:/usr/share/nginx/html/index.html
    ports:
      - 2223:2222
      - 8081:80
    restart: unless-stopped
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    container_name: haproxy
    hostname: haproxy #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PUBLIC_KEY_FILE=/config/id_rsa.pub
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=false #optional
      - USER_NAME=frontend #optional
    volumes:
      - ./config-haproxy:/config
    ports:
      - 2224:2222
    restart: unless-stopped
